version: '3'

networks:
  internal:
    # external: true

x-var: &ENVIRONMENT
  networks:
    internal:
  volumes:
    - .:/home/$NAME
  environment:
    - TZ=Asia/Tokyo
    - AWS_VAULT_BACKEND=pass
    - AWS_VAULT_PASS_PREFIX=$NAME
    - AWS_SESSION_TOKEN_TTL=3h
    - GPG_TTY=/dev/pts/1

services:
  aws-vault-terraform:
    <<: *ENVIRONMENT
    build:
      context: .
      args:
        USER: $NAME
        GROUP: $NAME
    image: kaduhiro/aws-valut-terraform
    container_name: aws-valut-terraform
    hostname: aws-valut-terraform
